### ISSUE TITLE
AP => Bluesky: content warnings

### ISSUE THREAD

**Issue by ShittyKopper** [snarfed/bridgy-fed#1001]
As an example example: [this](https://brain.d.on-t.work/notes/9sw59jdty9wukje4) AP note gets bridged over as [this](https://bsky.app/profile/kopper.brain.d.on-t.work.ap.brid.gy/post/3krow3t63rxl2) bsky post. losing all the context and making a post that, while potentially funny out of context (depending on the CW used) the first few times, could end up annoying towards people from bsky.

While there really isn't a *great* way to solve this problem without bsky getting a similar feature, simply prepending "CW: " or something of that sort, potentially with a link back to the original post (??? unsure on this part) should at least avoid most of the confusion this could result in.

**Comment by snarfed** [comment]
Thanks for filing! Ah, content warnings, takes me all the way back to #47. And agreed, not good, we can definitely do better. Thanks for the ideas.

**Comment by qazmlp** [comment]
This goes in the direction of bikeshedding a little, but I'd like to see something like

```
CN: summary

<web link to original post>
```

with "CN" (content notice) instead "CW" because in practice people do use that function very broadly and *afaik* not everything calls it a content warning.

I'd prefer the in-body link over a link preview attachment here because the latter can be obtrusively large in the GUI (which runs counter to CN/CW-use to collapse posts intentionally) and would most likely just duplicate some information already present otherwise, like name, handle, avatar and `summary`.

**Comment by AtiusAmy** [comment]
Is there an update on this

**Comment by snarfed** [comment]
Sorry, no, not a high priority right now. Should be straightforward though, PRs are welcome! The new code would go in [`granary.as2.to_as1`](https://granary.readthedocs.io/en/latest/source/granary.html#granary.as2.to_as1), should be pretty self contained.

**Comment by snarfed** [comment]
Thinking about this again. Out of curiosity, how much would you all dislike it if BF included the content notice/warning _and_ the actual content in the bridged Bluesky post?

I get that this isn't the spirit of content notices, and that content notices are an important part of fediverse culture for at least some people there, but they're obviously not part of the Bluesky culture. I wonder if it would be overall better UX for bridged posts to include both, instead of making Bluesky users constantly open external links in order to read a significant minority of bridged posts.

**Comment by qazmlp** [comment]
To and from *me* that'd be fine, ideally with `CN: ` prefixed.
Would break posts where that's used to hide a joke punchline, but those aren't really that common.

Be mindful of media attachments though, since AP lacks a real separate adult content system. (I guess Bsky could just label on their end if someone overdoes it tho.)

**Comment by AtiusAmy** [comment]
> Thinking about this again. Out of curiosity, how much would you all dislike it if BF included the content notice/warning _and_ the actual content in the bridged Bluesky post?
> 
> I get that this isn't the spirit of content notices, and that content notices are an important part of fediverse culture for at least some people there, but they're obviously not part of the Bluesky culture. I wonder if it would be overall better UX for bridged posts to include both, instead of making Bluesky users constantly open external links in order to read a significant minority of bridged posts.

I'd be fine with that, back on Twitter people were doing, so I don't think it's a problem

"CW: things

hi everyone it's things"

**Comment by snarfed** [comment]
Thanks all! I've deployed a first pass at this. Fediverse posts with content warnings/notices should now get bridged to Bluesky as:

```
[content notice]

post text
```

Let's see how that goes.

**Comment by tukinet** [comment]
Hello. This is my first post.

I was wondering if it would be possible for Bluesky to display only the warning message for posts with Content Warnings (CW) from Fediverse, and show a link to the original post instead of the main content? This would be incredibly helpful.

Bridgy Fed is a wonderful and attractive service, but unfortunately, some people give up using it solely because "posts with CW are displayed without being hidden on Bluesky." This is really unfortunate.

Content Warnings are frequently used when discussing things like newly released movies or manga, as a courtesy to people who are interested but haven't experienced the content yet. I do this myself. For such posts, it's standard practice to add hashtags and set them as "public" so they can reach others who enjoy the same content. Since they're "public," they inevitably appear on the bridged Bluesky account. This creates an uncomfortable situation where Bluesky users can't avoid spoilers, which really troubles me.

If it's technically difficult to "show only the warning message on Bluesky with a link to the original post," I would accept an alternative solution where "posts with CW aren't bridged at all." Though I realize this might face some opposition. Ideally, I prefer the first option of showing just the warning message with a link to the original post.

For reference, "poll" posts, which Bluesky doesn't support, aren't bridged even when they're set to "public." I thought perhaps CW posts could be treated similarly - as unsupported content that isn't bridged.

I would greatly appreciate it if you could consider this suggestion. Thank you for your time.

**Comment by snarfed** [comment]
@tukinet understood! Thanks for the feedback. It's definitely a judgment call; many people agreed with you, but many other people wanted the full content of CW posts to be bridged.

A good next step might be to ask Bluesky to consider adding support for content warnings themselves? https://github.com/bluesky-social/atproto/discussions

**Comment by tukinet** [comment]
@snarfed Understood. Thank you for your answer.
