### ISSUE TITLE
indieweb? to activitypub, content duplicated in 'name' element

### ISSUE THREAD

**Issue by macgirvin** [snarfed/bridgy-fed#1068]
Posts from tantek.com, which I assume is indieweb, duplicate the 'content' in the 'name' element, which several projects use as a post title. This leads to posts like the attachment - the bold blob on top is normally a short one-line title. It's not horrible, but it happens a lot and is probably unnecessary since the content is duplicated. Many projects only use the content field and don't support titles, but it's a bit jarring for those that do. In any case just wanted to bring this up if it's an easy fix and doesn't cause any other ill effects. 

![Screenshot from 2024-05-21 18-59-14](https://github.com/snarfed/bridgy-fed/assets/95073331/292b1e3b-001a-4567-a630-bee69774e096)

**Comment by snarfed** [comment]
Hey Mike, good to hear from you! And sorry for the trouble. You're right, this is coming from @tantek's site [tantek.com](https://tantek.com/), via [microformats2](https://microformats.org/wiki/microformats2), in this case because his site explicitly sets `p-name`, the mf2 equivalent of AS2 `name`, on his posts. Sounds like that may be unintentional, he's going to look into it!

**Comment by macgirvin** [comment]
Thanks for the help and the explanation - as I wasn't sure where to start looking.
