### ISSUE TITLE
Replies from mastodon marked "unlisted" does not get bridged to bluesky

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1086]
After trying it out with different settings, I've got it confirmed that when you answer someones bsky -> fedi bridged account in the fediverse, and have your settings on your answers as 'unlisted' the answer doesn't bridge back to bluesky. 

When I change the setting in mastodon to 'public', it gets bridged. Would it be possible to consider, to also bridge "unlisted" answers from the fediverse to bluesky?

**Comment by TomCasavant** [comment]
That's #1036 I think, discussion should probably be there but I agree if mark a *reply* as unlisted it should still be bridged

**Comment by snarfed** [comment]
Yes! This is #1036. BF intentional only bridges fully public posts and interactions right now, it if an abundance of caution, but I definitely get that that can be surprising for eg unlisted posts/replies and not necessarily what people want. I don't feel like I entirely understand all of the nuances of unlisted in the fediverse right now, across all the different implementations, but I should learn!

**Comment by DoktorZjivago** [comment]
Yes "unlisted" answers are visible to everyone, but does not show up in "trending topics" and such. :)

**Comment by snarfed** [comment]
Right! On Mastodon, at least. Afaik there are other differences on other projects, and I haven't dug into those enough to fully understand them yet.
