### ISSUE TITLE
ATProto => AP: if a non-bridged user replies, send them a DM opt-in request

### ISSUE THREAD

**Issue by mackuba** [snarfed/bridgy-fed#1205]
From: https://bsky.app/profile/mackuba.eu/post/3kvytnvcob72o

As a kind of extension to #966: same way as a DM bot will ping Fediverse users if they want to enable bridging when someone on Bluesky wants to follow them, the bot could also ping Fediverse users if they reply to a bridged post from Bluesky.

So e.g.:

- I make a post on Bluesky as mackuba.eu
- the post appears on mastodon.social as made by mackuba.eu@bsky.brid.gy
- johnmastodon@mastodon.social sees it in a hashtag feed and replies to it
- john mastodon has not enabled bridging to Bluesky (perhaps doesn't even realize that this post was bridged and that I wouldn't see the reply - a likely scenario imho)
- Bridgy DM bot on Fedi messages john: "hey, this reply to mackuba.eu that you wrote will not be seen by them unless you agree to bridge your account over to Bluesky - do you want this?"
- could send it just once after first such reply, or maybe at most once every X days or something, if they forget?

The goal is to decrease the number of replies from the other side which will be sent to the void and the OP will never see them.

**Comment by snarfed** [comment]
I love this idea! Totally makes sense. Thanks for suggesting it!

**Comment by mackuba** [comment]
Partial credit goes to Mike McCue ;)

**Comment by qazmlp** [comment]
This probably needs to cache a few (recent) bridge-directed interactions internally, which seems entirely fine to me in terms of data handling since the bridge is explicitly among the addressees.

Agreeing but then still not having those replies bridged would be very confusing, ymmv on likes, and I personally would expect boosts to *not* bridge retroactively.

**Comment by qazmlp** [comment]
This probably should say that for now only 'Public' replies are bridged when the DM's recipient is on ActivityPub.

**Comment by snarfed** [comment]
Sure! I'm reluctant to duplicate too much of the docs in these DMs, but that sounds like a reasonable one.

**Comment by snarfed** [comment]
OK! First pass at this is done, DMs are rolling out to both fediverse and Bluesky users. I expect to tweak the text, but the functionality seems to be working. Tentatively closing.

**Comment by snarfed** [comment]
For the record, this works right now, but only sometimes, due to eg #1329, and it will probably happen even less in the future due to eg #1341. The tradeoff here is that processing and handling more activities from non-bridged users like this directly increases our hosting costs, which are already too high. Maybe in the future with more funding, we'll come down differntly on that tradeoff! But not ritht now.

**Comment by shiribailem** [comment]
So, regarding the filtering and power consumption, etc.

How much impact would it be relatively to incorporate a semi-static reply during the filtering process? My thought is to take where it drops it currently and maybe send it to a lighter microservice that does nothing but send the message?

And maybe reduce load further by just using a queue system there, which also means it can maybe check if it's in the queue first.

**Comment by snarfed** [comment]
Definitely! We already do all of that.

We currently average 20-30qps (1.7-2.6M/day) of incoming AP activities that we have to parse, process, verify signatures, etc. Of those, we actually bridge 2-3qps. The corresponding ATProto numbers are 500-1000qps incoming records, 3-5qps bridged. These numbers aren't our only cost drivers, but they are a substantial one.

Bridgy Fed costs too much to run right now (see #1149), so sadly cutting costs is a higher priority than nice-to-have features like this. Hopefully I can revisit once costs are more manageable!
