### ISSUE TITLE
ActivityPub -> ATproto/BSKY handle cleanup or shortening

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1390]
Is there any possibility of the bridged BSKY accounts (from fedi to BSKY) to have some sort of better, short handles?

I understand why it’s the way it is currently, but I’m not familiar enough with ATproto to know if there’s any room to shorten these. 

For example, my actual BSKY account handle is `@sig.dog`, nice and short, and easy to remember or verbally tell someone. 

My bridged fedi account is `@sig.furries.club.ap.brid.gy` which is…long, to say the least. 

If shortening these bridged handles is out of scope, I know there was some talk about migrating BSKY accounts to BF accounts. This may also solve this issue, so long as the BF account could also bridge the Fedi posts.

apologies if this has all been answered! I’ve been digging through the issue history to search for this info but I may have missed it.

**Comment by snarfed** [comment]
Yes! Popular request, @kdederichs asked for the same thing earlier today, https://github.com/snarfed/bridgy-fed/issues/1387#issuecomment-2419530319.

I plan to start on custom domain handles for fediverse => Bluesky bridged accounts soon, that's #826, feel free to follow along there.

Migrating existing Bluesky accounts into BF is #1137. (Pretty unlikely, to be honest.)

Tentatively closing, since those issues are already tracking these ideas. Feel free to reopen if I missed anything!
