### ISSUE TITLE
AP => ATProto: Bridge not working

### ISSUE THREAD

**Issue by atouu** [snarfed/bridgy-fed#1392]
Hi! I recently set up bridgy fed to bridge my mastodon to bluesky. However, neither of my posts nor updates are appearing in my bridged account on https://bsky.app/profile/atou.masto.ai.ap.brid.gy. https://fed.brid.gy/ap/@atou@masto.ai returns Not Found too.

**Comment by bitten2up** [comment]
i can second, only replies and renotes to messages on bsky seem to federate

**Comment by qazmlp** [comment]
`@atou@masto.ai` says it was created yesterday, which normally doesn't meet the requirements…
I think that's likely the reason the profile says "Not Found" at the Bridgy Fed website.
(Don't worry, you can try this again later. Just **do not block** the bridge as that's irreversible for now!)

@snarfed it looks like the spam filter doesn't prevent bridge account creation on Bluesky, which looks like a bug to me.

@bitten2up I'm not a maintainer here so I may be overstepping a bit, but: Could you link a status that should have been sent to Bluesky but wasn't? It's difficult to diagnose issues like this without examples.

(Bluesky is also having technical difficulties right now because [it's under very heavy load](https://bskycharts.edavis.dev/edavis.dev/bskycharts.edavis.dev/index.html). It seems some actions were showing up there with a large delay even Bluesky->Bluesky.)

**Comment by bitten2up** [comment]
> @bitten2up I'm not a maintainer here so I may be overstepping a bit, but: Could you link a status that should have been sent to Bluesky but wasn't? It's difficult to diagnose issues like this without examples.
> 
> (Bluesky is also having technical difficulties right now because [it's under very heavy load](https://bskycharts.edavis.dev/edavis.dev/bskycharts.edavis.dev/index.html).
> It seems some actions were showing up there with a large delay even Bluesky->Bluesky.)

https://social.bitten2up.dev/notes/9zh93cjhmxp60046

and some bridged replies

https://bsky.app/profile/bitten2up.social.bitten2up.dev.ap.brid.gy

**Comment by qazmlp** [comment]
Interesting. The post is clearly public but it doesn't show up on [your status page](https://fed.brid.gy/ap/@bitten2up@social.bitten2up.dev).

This should be enough info to debug it though.
(I can't help further since I don't have access to the internal logs.)

**Comment by qazmlp** [comment]
I wonder if it's because of the explicit `"inReplyTo": null`.
Mastodon just omits that field for top-level posts, and the other differences seem like they'd be the same for replies.

**Comment by snarfed** [comment]
Thanks @qazmlp! @bitten2up did you accept @bsky.brid.gy@bsky.brid.gy's follow? This sounds like your instance isn't delivering your posts to Bridgy Fed, which that would cause. https://fed.brid.gy/docs#fediverse-get-started

**Comment by bitten2up** [comment]
> Thanks @qazmlp! @bitten2up did you accept @bsky.brid.gy@bsky.brid.gy's follow? This sounds like your instance isn't delivering your posts to Bridgy Fed, which that would cause. https://fed.brid.gy/docs#fediverse-get-started

ah, just double checked, its bugging out hard, no clue why its stuck on processing. ill try to see if there are any relevant logs for it

![Screenshot_20241018-155044.png](https://github.com/user-attachments/assets/ccac1bb9-9835-403b-ba8d-1304b2c528ba)

**Comment by bitten2up** [comment]
ok thats weird, ill have to look farther when i get home though 
![Screenshot_20241018-160936.png](https://github.com/user-attachments/assets/75c0d5de-0096-4fb9-a007-161e917784a4)

**Comment by bitten2up** [comment]
after way too fucking long... we did it...

**Comment by snarfed** [comment]
Woo, congrats!
