### ISSUE TITLE
Bluesky Profile banners not visible on Misskey/Sharkey

### ISSUE THREAD

**Issue by Donad678** [snarfed/bridgy-fed#1408]
I noticed that profile banners from Bluesky users are not visible on my Sharkey instance and after trying the same user on a remote misskey instance I got the same problem. On Mastodon the profile banner appears properly.

**Comment by Tamschi** [comment]
This happens because Bridgy Fed serves an array as `image`, which [is permitted both for `icon` and `image`](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-icon).
Misskey fails to handle that [here](https://github.com/misskey-dev/misskey/blob/15ae1605ec199792cd651073b1c6de480a7eeabe/packages/backend/src/core/activitypub/models/ApPersonService.ts#L237-L238). I'll submit a patch to fix that.

That said, I think it would make sense for Bridgy Fed to serve only the `banner` as `image` while the `avatar` is the `icon`.

**Comment by snarfed** [comment]
Thank you for the sleuthing @Tamschi!

**Comment by Tamschi** [comment]
My fix was just merged, so it should start working in Misskey 2024.10.2-alpha.2 or later (as well as any forks, eventually).

**Comment by Tamschi** [comment]
@snarfed Do you consider this closed or do you want to adjust how profiles are translated?

I don't think there is any popular software where this would cause issues, but it may be a bit odd if the avatar appears in a banner rotation if an instance eventually supports multiple.
