### ISSUE TITLE
Can't follow @bsky.brid.gy@bsky.brid.gy via mostr.pub

### ISSUE THREAD

**Issue by WinLinux1028** [snarfed/bridgy-fed#1436]
I'm using Nostr and I want to bridge with Bluesky.
So I tried to follow [bsky.brid.gy_at_bsky.brid.gy@mostr.pub](https://njump.me/bsky.brid.gy_at_bsky.brid.gy@mostr.pub) but not bridged.

**Comment by snarfed** [comment]
Hi! Sorry for the trouble. Have you looked at https://fed.brid.gy/docs#troubleshooting ?

**Comment by WinLinux1028** [comment]
I probably shouldn't be on this one.

**Comment by snarfed** [comment]
Hmm! Sorry if we weren't able to help. Tentatively closing, but feel free to reopen.

**Comment by juanro49** [comment]
> I'm using Nostr and I want to bridge with Bluesky. So I tried to follow [bsky.brid.gy_at_bsky.brid.gy@mostr.pub](https://njump.me/bsky.brid.gy_at_bsky.brid.gy@mostr.pub) but not bridged.

I know other Nostr accounts that have enabled Bluesky bridge with [momostr.pink](https://momostr.pink/) Nostr bridge instead of [mostr.pub](https://mostr.pub/) Nostr bridge

Examples:
- https://bsky.app/profile/npub1qspus6smkn8mcdxg5jflh50s69vdgtwsd5p74gmjpzp2qekn5duqfv5afj.momostr.pink.ap.brid.gy
- https://bsky.app/profile/npub1hgclq59xd44wuulmykzqtfz0elaxvt3y0p8xv5y5f78u95cgjsnshhy0we.momostr.pink.ap.brid.gy

Address of @bsky.brid.gy@bsky.brid.gy with momostr.pink bridge to follow it:
- bsky.brid.gy_at_bsky.brid.gy@momostr.pink
- npub1pqr3g2gk3vsnrqk9kwfqqcxc6d5cwjr0hyc0nlzz9py5nf92vd9sn02sck

**Comment by snarfed** [comment]
Hmm, sorry @juanro49! Have you looked at https://fed.brid.gy/docs#troubleshooting ?
