### ISSUE TITLE
Cannot follow @bsky.brid.gy@bsky.brid.gy from my Mastodon account @_Jordan@c.im

### ISSUE THREAD

**Issue by jordanekay** [snarfed/bridgy-fed#1498]
When I try to follow the account, the follow request is never accepted, and the account never follows me back. Is it because I am on one of the smaller instances and am not making it past the spam filter?

**Comment by Tamschi** [comment]
It's because your handle starts with an underscore. Bridgy Fed normally replaces those with a dash, but that's not valid at the start, end or adjacent to a `.` in ATProto handles. More info here: https://fed.brid.gy/docs#troubleshooting

As the documentation says, this may be improved in the future. (#982)

**Comment by jordanekay** [comment]
I am seeing the same behavior when trying to follow from a different account of mine, @jn@c.im. Perhaps it’s the server itself that is being rejected?

**Comment by snarfed** [comment]
https://c.im/about doesn't show that c.im is blocking or limiting Bridgy Fed. Have you looked at everything else in https://fed.brid.gy/docs#troubleshooting ?

**Comment by Tamschi** [comment]
See also #758 for how we'll hopefully avoid confusion in that regard in the future.
