### ISSUE TITLE
AT => any: Allow opt-in while hidden from logged-out users

### ISSUE THREAD

**Issue by vyv03354** [snarfed/bridgy-fed#1550]
Reported here (Japanese): https://bsky.app/profile/tukinet.info/post/3lb7e3a2gl22q

If "Discourage apps from showing my account to logged-out users" option is enabled, Bridgy Fed will not allow to start bridging. If the bridging is already started, however, posts will be bridged even if the option is checked. Is this an expected behavior? If it is not, please add a way to opt-in bridging even if the option is enabled, because the reported user desires the current behavior.

**Comment by Tamschi** [comment]
That's an interesting one. I think the behaviour is intentional, since hiding an account from logged-out users shouldn't just delete the fediverse bridge account (as that would sever all connections on ActivityPub).
However, it's not possible to translate the setting to ActivityPub, so for example Misskey instances can be used without login to view the account, if the handle is known.

Is it okay if I change the title to "AT => any: Allow opt-in while hidden from logged-out users", since this is a feature request?

@snarfed This could make sense with an `--allow-logged-out-viewing` flag added to the `start` command via DM. I don't think we should present that proactively in the `help` response, but we could surface it in #758 if this is why bridging fails.

**Comment by Tamschi** [comment]
Oh, I just saw #1549! That makes this easier, I think.

**Comment by vyv03354** [comment]
> Is it okay if I change the title to "AT => any: Allow opt-in while hidden from logged-out users", since this is a feature request?

OK, I changed the title.

**Comment by snarfed** [comment]
#1293 now includes detecting when a Bluesky user changes their "hide from logged-out users" setting. Other than that, as discussed, I don't really plan to allow Bluesky users with that setting enabled to use the bridge. Sorry for the bad news.
