### ISSUE TITLE
When someone follows a bridged account, initiate the bridging process for the follower

### ISSUE THREAD

**Issue by agharbeia** [snarfed/bridgy-fed#1574]
For example: When a user on BlueSky follows my Mastodon account that is bridged into BlueSky, this means I could   potentially want to follow them as well.

This includes notifying me when the other account is eventually bridged, as in #1321

**Comment by snarfed** [comment]
Hmm, I'm confused. You mean, when someone follows you, you want the bridge to make you automatically follow them too? That's...not how following works in general, so it would probably be an unpleasant surprise for most people.

(Also, Bridgy Fed can't make normal Mastodon accounts or normal Bluesky accounts follow anyone. 🤷)

**Comment by Tamschi** [comment]
@snarfed This is a feature request to auto-bridge followers of bridge accounts, I think.

(This is very unlikely to happen on the fediverse, but for Bluesky #1471 could make this feasible eventually.)

**Comment by snarfed** [comment]
Ah, got it, ok, thanks. Yeah this is very similar to #1535. The problem is that many/most people who follow a bridged account won't know that they're bridged, or even that the bridge exists or what it is, so auto-bridging them would be a surprise.

Right now Bridgy Fed is opt in on the fediverse and Bluesky. We may eventually let instances switch themselves to opt out, #1305, or even entire protocols, eg #1471, but on protocols and instances that stay opt in, I don't really ever plan to auto-opt-in people. Trying to keep things as simple, understandable, and black and white as possible.

**Comment by agharbeia** [comment]
Thanks, @Tamschi . Yes, that's what I meant.

I, too, agree that bridging should be opt-in. It's also more practical, and resource effecient.

So perhaps a slightly modified procedure, whereby an invitation to bridging is extended to the follower-party, linking to an introductory resource about BridgyFed, and inviting them to follow the bot, if they would like to be bridged.

**Comment by snarfed** [comment]
Agreed! That's #1340
