### ISSUE TITLE
Relaunched instance, old account still cached

### ISSUE THREAD

**Issue by cmdr-nova** [snarfed/bridgy-fed#1594]
Not sure if this is an issue anyone else is having, because it may be unique to me in my software-hopping adventures. But it seems I cannot get the brid.gy.fed account to follow me back after relaunching my instance on the same domain (moved from managed hosting to self hosting).

Seems maybe authentication cache needs to be cleared (or something similar)?

For reference, I'm over at [mkultra.monster/@cmdr_nova](https://mkultra.monster/@cmdr_nova)

**Comment by snarfed** [comment]
Hey, sorry for the trouble. And oof, looks like your old instance sent out a `Delete` for your https://mkultra.monster/users/cmdr_nova actor? AP doesn't have a good or consistent way to undelete actors, I suspect lots of fediverse software and instances will have a hard time with this.

**Comment by cmdr-nova** [comment]
Oof, if it can't be undeleted, can it be reset as if I was newly following? I probably should have taken better precautions on my part, but what's done is done I guess lol

**Comment by Tamschi** [comment]
> Hey, sorry for the trouble. And oof, looks like your old instance sent out a `Delete` for your https://mkultra.monster/users/cmdr_nova actor? AP doesn't have a good or consistent way to undelete actors, I suspect lots of fediverse software and instances will have a hard time with this.

It should be fine on most of them. It's fine on Mastodon.

When an ActivityPub actor is `Delete`d, it should be (functionally) purged from the database rather than tombstoned.
(In practice there's a DB lock while associated data is purged, but you can do this without a transaction or lock by foreign-keying on an internal GUID rather than the `@id` directly.)

Fetching an actor is always done directly from source, so if that succeeds, that's a safe synchronised signal to populate the actor (from scratch). Conversely, when an instance deletes an actor, it first makes the JSON-LD document inaccessible and then sends out a `Delete`. They may also want to respond to Authorized Fetch attempts targeting that `@id` by submitting the `Delete` to the fetcher's (shared) inbox.

**Comment by snarfed** [comment]
@Tamschi true! `Delete` of an actor destructive in that it severs all follower relationships, and I had some difficulty getting fediverse instances to un-delete a deleted actor, but I was eventually able to get most of them to at least recognize it as usable again.

**Comment by snarfed** [comment]
@cmdr-nova I've manually un-deleted your actor in BF, feel free to try following the bot account again.

**Comment by cmdr-nova** [comment]
Looks like refollowing worked! Thanks a whole bunch 😎

**Comment by cmdr-nova** [comment]
It looks like the bridged version of my account on bsky appears as though the handle is invalid, assuming this will fix itself (sorry I'm doing everything on my phone at the moment)

![image](https://github.com/user-attachments/assets/ad500cd8-4c34-4df1-b1bc-97df40d0745f)

**Comment by snarfed** [comment]
Yes! Sorry about that, should be fixed soon.
https://bsky.app/profile/cmdr-nova.mkultra.monster.ap.brid.gy
https://bsky-debug.app/handle?handle=cmdr-nova.mkultra.monster.ap.brid.gy
