### ISSUE TITLE
Using granary... how does PSHB work?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#19]
The Bridgy Fed page says one can just use Granary to convert mf2 content to Atom for federation use... it shows putting a "hub" argument in to the granary URL, but would my site need to support something (like PSHB notifications for the HTML page) in order for this to work, or does it poll?

**Comment by snarfed** [comment]
hi! heh, you've found one of the big hand waves in the docs.

the PSHB/WebSub requirement is because some OStatus fedsocnets require it, e.g. GNU Social and Mastodon before ActivityPub. afaik this is primarily for post distribution, so that followers on other instances will get your posts.

Fridgy Fed itself doesn't currently implement WebSub at all, hub or polling or otherwise. it's just a placeholder to satisfy those fedsocnets' checks. using it obviously won't get your posts distributed - which is #18 - but that's a kind of reasonable corner to cut to get started.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
