### ISSUE TITLE
granary hub set to topic URL?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#25]
Shouldn't https://github.com/snarfed/bridgy-fed/blob/master/webfinger.py#L77 use the hub from the next line, if any, not `resp.url` for the hub parameter?

**Comment by snarfed** [comment]
sure! that'd be a good update.

the awkward part is that bridgy fed itself doesn't actually care about or use PuSH anywhere. it's only needed for (some) ostatus nodes to accept and interoperate with us. it's also part of #18, which is slightly outside bridgy fed's scope, but is definitely central to the larger UX of "make my indieweb site talk to the fediverse."

i've avoided tackling that question comprehensively so far, mostly because i don't personally interact with the fediverse much at all, so i can't easily self dogfood. still definitely needs some love and attention though!

**Comment by snarfed** [comment]
Closing because we're deprioritizing Atom and OStatus entirely: #283
