### ISSUE TITLE
ImportError: No module named django

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#26]
This is what I get when running the setup instructions from the readme.

If I instead run `pip install -r requirements.freeze.txt` I get this when running the tests:

`ImportError: No module named django.template.loaders`

**Comment by snarfed** [comment]
argh. sorry for the trouble, and thanks for trying!

mind posting the full stack traces? definitely odd, since nothing in bridgy fed, granary, or oauth-dropins imports or uses django directly. bridgy fed does use django_salmon, but [my fork](https://github.com/snarfed/django-salmon/), which localizes the django imports so that they don't actually happen.

are you using the app engine SDK? or gcloud? which version?

also, if/when you get past this, you may need to `pip uninstall oauth-dropins; pip install oauth-dropins==1.12`. i'll update that in `requirements.freeze.txt`.

**Comment by singpolyma** [comment]
http://termbin.com/o7gk

I used gcloud to install the app engine SDK, since that's the only way I could find it anymore.  `google-cloud-sdk-197.0.0-linux-x86_64`

**Comment by singpolyma** [comment]
Ok, my bad. I installed `app-engine-python-extras` as per the README with gcloud and now it works
