### ISSUE TITLE
Do profile changes get propagated?

### ISSUE THREAD

**Issue by fancypantalons** [snarfed/bridgy-fed#298]
When I first syndicated a post out from my site, I didn't realize my h-card was messed up, and the link back to my profile was broken.  As a result you can now find that this link:

https://mastodon.social/@brettk@b-ark.ca

Now takes you to the wrong place on my site.

Does BF detect changes to the h-card and propagate those changes?  Heck, is this even something that BF can address?  I could imagine also changing profile photos, names, or other details having similar issues.

**Comment by snarfed** [comment]
Hmm! The two places Mastodon and other fediverse servers look for profile information like this are Webfinger, https://b-ark.ca/.well-known/webfinger?resource=acct:b-ark.ca@b-ark.ca , and your ActivityPub actor URL, https://fed.brid.gy/b-ark.ca . BF only caches those for up to 15s max each, and otherwise re-fetches and converts your home page h-card.

Both of those look ok for you right now, pointing to your home page and similar URLs and not that post. I don't know how long mastodon.social will cache it, but hopefully not too much longer?

**Comment by fancypantalons** [comment]
I guess we'll see.  (web)fingers crossed!  Thanks!

**Comment by snarfed** [comment]
For posterity, sending an `Update` activity for the actor to a given instance will successfully update that instance's copy of your profile. I don't know how I'd integrate that into BF yet, especially without regularly polling everyone's site. 😐
