### ISSUE TITLE
Add a bookmarklet for following someone

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#414]
To be able to more easily initiating a follow of someone, it'd be nice to

I notice that a follow sends a POST to `https://fed.brid.gy/follow/start`:

```
address=https://indieweb.social/@jamietanna
&
me=https://www.jvt.me
```

Would it be possible to set up a means to trigger this via a GET, so we can add it as a bookmarklet script?

**Comment by snarfed** [comment]
Interesting! I'm reluctant to make this support GET, since it's a meaningful state change, and GETs always proliferate via crawlers, browser prefetches, etc. I'm open to other ideas though. Browser extension or share target that creates a u-follow on your site via Micropub is one option. Heavyweight, but would work. That's what I currently do, with https://wordpress.org/plugins/indieweb-press-this/ . Alternatively, are there browser extensions that let you set up custom HTTP request templates filled in with parts of the current page, eg the URL?

**Comment by jamietanna** [comment]
Ah sorry to be clear I mean a GET that I can land on and then initiate the flow rather than it doing it in the background

**Comment by snarfed** [comment]
Oh! You can auto-fill the follow address text field on eg https://fed.brid.gy/user/www.jvt.me/following with the `address` query param, eg https://fed.brid.gy/user/www.jvt.me/following?url=@x@y . Does that help?

**Comment by jamietanna** [comment]
Awesome, yep that works! For future reference for folks I have this:

```
javascript:window.location='https://fed.brid.gy/user/www.jvt.me/following?address='+encodeURIComponent(location.href);
```

As a bookmarklet in my browser.
