### ISSUE TITLE
Possible to post without backlink

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#42]
I wanted to file this request, because I remembered something from last week: I didn't configure to render a backlink yet on my source pages to https://fed.brid.gy/ for 'notes' (they are now, so it's fine). However, the post did show up when using fed.brid.gy. Skimming the code, I don't see a check for a backlink anywhere, unless I missed it completely.

If it's there, don't mind me of course, but I guess it can't hurt for a double check :)

**Comment by snarfed** [comment]
so you send webmentions to https://fed.brid.gy/webmention with target https://fed.brid.gy/, and they work even though your posts don't link to https://fed.brid.gy/ ?

if so, yes, that's expected. bridgy fed technically violates the webmention spec in that it doesn't check for a link to the target, since the webmention is just used as a trigger. let me know if you think that's a problem!

**Comment by swentel** [comment]
Oh, no that's not necessarily a problem for me, it's just that it's in the docs, and couldn't see in the code, while https://brid.gy does this check. So if it's not necessary, the following part can probably be changed a bit (and I can change it in the Drupal README too): 

> To use it, create an IndieWeb post, like, repost, reply, or follow as usual, and include a link to https://fed.brid.gy/ in that post

**Comment by sknebel** [comment]
Unless I misunderstand the details, doesn't this mean anyone can go through the archives of a bridgy fed user and have bridgy fed publish their old posts in some annoying random order?

**Comment by snarfed** [comment]
@sknebel heh, yes, good point. we probably do need a backlink check for the same reasons that bridgy publish does.
