### ISSUE TITLE
Key export?

### ISSUE THREAD

**Issue by sknebel** [snarfed/bridgy-fed#62]
From my (limited) understanding of ActivityPub, once you use AP for a domain and interact with the wider world you'll need access to the private keys used for the various signature bits if you ever intend to use some other service/software. 

Thus it'd be great if I could export the key used by bridgy-fed.

**Comment by snarfed** [comment]
very true! usually this isn't necessary because your address is based on your host, eg mastodon.social, and migrating to another service or software would also change your host. bridgy fed is obviously different, though, since it uses your own domain as your host.

i don't currently plan to add a programmatic or UI way to do this, but I'm happy to send you your private key manually if you want! just let me know where.

**Comment by sknebel** [comment]
Thanks. I'm currently looking at options to use AP with my site, so I don't need it right now, but this seemed like something to figure out before I commit to something.
