### ISSUE TITLE
Wordpress posts no longer being picked up

### ISSUE THREAD

**Issue by brentajones** [snarfed/bridgy-fed#625]
My last post that Bridgy Fed accepted was a month ago (https://blog.bjones.net/2023/07/11/2808/). Since then I've made at least a couple posts that should've federated, but didn't (https://blog.bjones.net/2023/08/25/2827/ and https://blog.bjones.net/2023/08/18/2822/).

This could be user error but I've checked everything I can think of to check (webfinger seems ok, my webmentions seem ok). My user page (https://fed.brid.gy/web/blog.bjones.net) doesn't show any errors.

I know subdomains have been tricky, so perhaps that's it?

**Comment by snarfed** [comment]
Ruh roh, looks like a bug. Thanks for reporting, will fix.

**Comment by snarfed** [comment]
@brentajones looks like the issue is that your posts' `author` mf2 (specifically a `<link rel=author>`) points to https://blog.bjones.net/author/blog_6a4uto/ , which BF is cowardly not assuming is the same as https://blog.bjones.net/ . If you change that to https://blog.bjones.net/ , it should work!

**Comment by brentajones** [comment]
That did it. Thanks so much!

**Comment by brentajones** [comment]
That did it. Thanks so much!
