### ISSUE TITLE
IndieWebify.Me correctly validates h-card, bridgy does not

### ISSUE THREAD

**Issue by BeeFox-sys** [snarfed/bridgy-fed#626]
For site https://beefox.xyz

**Comment by BeeFox-sys** [comment]
it was an issue with my card, the h-card standard says that representive cards can be either via a link to the same site with a class of `u-url u-uid`, OR with links with `rel=me` and the `u-url` class, however bridgy seems to only check for the former.

my card had a typo meaning only the latter was a valid way of identifying the representive card

**Comment by snarfed** [comment]
Hmm! Sorry for the trouble. Glad you figured it out!

As far as I know, Bridgy Fed should definitely support `rel=me` links and not require `u-uid`. I don't have a record of your original home page's contents, so I can't look myself, but feel free to change it back or otherwise follow up if you're interested.

**Comment by snarfed** [comment]
^ I've updated the docs and UI link to make the representative part clearer. @BeeFox-sys please do let me know if you can reproduce a bug where Bridgy Fed doesn't accept the `rel=me` version.
