### ISSUE TITLE
On opt out, delete user in bridged networks

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#783]
When we bridge someone, and then they opt out, we should proactively delete their bridged accounts in all other networks, eg send an AP `Delete` activity to all followers' instances.

**Comment by snarfed** [comment]
One difficulty here is that we need to deliver the `Delete` only to followers in the given network, which `Protocol.receive` isn't currently set up to do. Maybe add a `target_protocol` kwarg there?

**Comment by qazmlp** [comment]
You may want to broaden this and send it to all known instances on the network, since accounts can become cached somewhere just by searching for them.

**Comment by snarfed** [comment]
That is indeed how Mastodon does it!

I'm actually curious how broad their "known instances" is. For an arbitrary instance that discovers an actor purely by searching, you'd need to extract the instance host from the HTTP user agent, which is unreliable at best. (Or the HTTP Signature's `keyId`, which is better, but only some instances sign their fetches.)

Regardless, Bridgy Fed isn't set up to do this right now, but you're right, it's a good idea.

**Comment by snarfed** [comment]
The extreme answer here is #552, but that feels a bit _too_ extreme and heavy.

**Comment by snarfed** [comment]
One difficulty here is what happens if someone bridges their account, then un-bridges it, then re-bridges it. Current fediverse servers may not let us delete an actor and then recreate it with the same id.

Ideally we should test with a bunch of them. Whee. Alternatively, for now, we could document loudly that once you've un-bridged an account, you can't re-bridge it.

**Comment by snarfed** [comment]
Still figuring this out in Bluesky too: https://github.com/bluesky-social/atproto/discussions/2503

**Comment by qazmlp** [comment]
I think the expectation on the fediverse is that ids _may be reused_, but _not necessarily by the same identity_.
(You should probably throw away the AT did if a receive a _remote_ 'Delete' for this reason, if you normally hold onto it when unbridging. You should still receive the remote 'Delete' even while an account isn't currently bridged.)

Mastodon for example [doesn't reserve the username](https://github.com/mastodon/mastodon/blob/89f89d738f5840c80ff938f8bf6734cdafe0fa83/app/lib/activitypub/activity/delete.rb#L16), but [severs all relationships irretrievably](https://github.com/mastodon/mastodon/blob/89f89d738f5840c80ff938f8bf6734cdafe0fa83/app/services/delete_account_service.rb).
(However, note that [Mastodon sets a database lock for up to two hours](https://github.com/mastodon/mastodon/blob/89f89d738f5840c80ff938f8bf6734cdafe0fa83/app/lib/activitypub/activity/delete.rb#L15), which may prevent the account from being re-created too quickly… not really a problem since it'll just get re-pulled after that, but if you e.g. try to restore follows, since they'd still exist on the AT side, that could cause some weirdness for a few hours before it settles.)

Misskey [sets a flag](https://github.com/misskey-dev/misskey/blob/20c0bd9ddb86cd194be52d3f7c297ad5fd148a12/packages/backend/src/core/activitypub/ApInboxService.ts#L465-L488). I didn't see anything that would indicate this actually prevents updates to the user, but also didn't see anything explicitly clear it.

**Comment by snarfed** [comment]
> I think the expectation on the fediverse is that ids _may be reused_, but _not necessarily by the same identity_.

Wow, that's surprising. Usually not a good idea for all sorts of reasons, especially in security/auth contexts like this. 🤷 https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization

Otherwise, yeah, the UX mismatch here is difficult. It's very easy to block, unblock, and re-follow the bot user. If we can't undelete a bridged account, users will end up doing something they can't undo. 😕 Fortunately [we have a lead on undelete-able delete for Bluesky](https://github.com/bluesky-social/atproto/discussions/2503#discussioncomment-9504290), at least. As for the fediverse, sounds like I need to do some tests.

**Comment by qazmlp** [comment]
> > I think the expectation on the fediverse is that ids _may be reused_, but _not necessarily by the same identity_.
> 
> Wow, that's surprising. Usually not a good idea for all sorts of reasons, especially in security/auth contexts like this. 🤷 https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization

In practice, most fediverse software does reserve handles on delete, but yeah, it's very much possible for admins to release them, and there is nothing on the protocol level that really enforces that level of uniqueness. (It doesn't help that for convenience/"search"-interop it's helpful to use the profile's web URL as id.)

Brittleness aside, fediverse servers generally really don't make for good identity providers.
I think there's some expectation (in practice, not theory?) that public keys are unique, but those in turn can rotate afaik.

**Comment by snarfed** [comment]
Got this working for Bluesky! By serving a `#tombstone` event over `subscribeRepos`, as discussed in https://github.com/bluesky-social/atproto/discussions/2503#discussioncomment-9504290. Example: https://bsky.app/profile/martent.mastodon.social.ap.brid.gy

**Comment by snarfed** [comment]
Next step is fediverse. Probably need to refactor `Protocol.receive` a bit so it can take an optional target protocol and only deliver to followers in that protocol.

**Comment by snarfed** [comment]
Done! This now works for Bluesky => fediverse as well. If you're on Bluesky, and you follow the bridge, and then block it, it will delete your bridged fediverse profiles on all of your followers' instances.
