### ISSUE TITLE
Opting out

### ISSUE THREAD

**Issue by michaelnordmeyer** [snarfed/bridgy-fed#795]
I'd like to opt-out, because I believe creators should be in control who's publishing what and where. That means it should be opt-in, especially because it's not hard to create another fediverse account for just publishing their own feed.

I don't think opting out by e-mail is reasonable, because it exposes an otherwise not exposed e-mail address.

I also don't think putting a hashtag on a profile is reasonable, because it litters the profile with unrelated info and won't work for many "services".

Implementing https://github.com/snarfed/bridgy-fed/issues/783 is important to achieve a full opt-out, because I don't want a feed with my name on lingering around.

And, last but not least,

> [Opt out isn’t as conservative as opt in, but opt in results in far fewer users, and users are critical for a bridge to be useful.](https://snarfed.org/2023-11-27_re-introducing-bridgy-fed)

is seriously uncool and disrespects the people who created the content in the first place.

You can gather the feed in question from my GitHub profile.

**Comment by snarfed** [comment]
Done! I've opted out your site. And I hear your feedback, it does make sense in some ways, and you're definitely not alone.

I've been thinking about this a lot recently, from a number of angles. I'm about to publish this, I'm curious what you think: https://snarfed.org/2024-01-19_moderate-people-not-code

**Comment by michaelnordmeyer** [comment]
There's a lot to take in. In general, I think context collapse is a problem, because users lose the ability to judge the reach of their posts.

If I don't have a Nostr account, I don't want my Mastodon posts be published there automatically.

It's different to some people just subscribing to a RSS feed or following from another instance. That's just a way of consuming the content. It's not republishing.

And bridges are exactly the thing, which ordinary users don't know about. Bridges could not only alienate a subset of users, but also whole communities of both sides of the bridge.

As to publishing the post, I think it's better to make series of posts where each post focuses on a certain aspect, but all are published at the same time, linking each other.

**Comment by snarfed** [comment]
Thank you for reading it! There is a lot, you're right.

I definitely get the context collapse point, I feel it too. The more I thought through it though, the more confused I got.

As one example from the post, Mastodon servers feel like similar context to each other, but Lemmy and Peertube server don't nearly as much, and yet we in the fediverse accept (I think?) that Mastodon posts federate to those servers, and that Lemmy threads and PeerTube videos federate back, etc. Even much farther than just to our own followers, due to Mastodon relays, searches, replies, etc.

Embeds and quotes are another example. Articles and blog posts regularly quote and embed other posts and comment on them, without the original author ever knowing. This seems like an inevitable part of publishing anything publicly.

Anyway. I'm still obviously working through all this myself. Thank you again for reading, and for your thoughts.
