### ISSUE TITLE
Bluesky: add label to bridged profiles

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#827]
Label docs: 
* Lexicon: https://github.com/snarfed/atproto/blob/main/lexicons/com/atproto/label/defs.json
* Labels currently handled by the official client/SDK:
  * https://github.com/bluesky-social/atproto/blob/main/packages/api/docs/labels.md
  * https://github.com/snarfed/atproto/blob/main/packages/api/definitions/labels.json

**Comment by KDederichs** [comment]
Sorry for the ping in this old issue but how do I get those labels to actually show up?
If I visit a profile I know to be bridged to the Fediverse in the app there is no label (making it a bit tedious to see who actually bridged or not).
Is there some sort of labeler I need to subscribe to to see this?

**Comment by qazmlp** [comment]
@KDederichs These are only "bridged from" labels on the bridge accounts I believe, while accounts native to Bluesky are not labelled at all by Bridgy.

(Additionally, these labels don't really work in a meaningful capacity for end users, since there's no labeller defining them.)

It would be helpful if there was a central labeller (for all networks combined) that surfaced these as badges on/to users (which could then also be used to provide that badge for native accounts bridged to elsewhere) 🤔

**Comment by KDederichs** [comment]
Ah yeah I see.
Yeah I was looking for something like:
You visit a Bluesky profile in the Bluesky app and then there would be a "Bridgy Federated" label or something so you can see with one glance that you could follow that person from the fediverse.

**Comment by qazmlp** [comment]
I think I'll file a feature request for this. It's something I've seen requested a few times and I think I have a decent understanding of some caveats when implementing it.
