### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by Higgs1** [snarfed/bridgy-fed#869]
Good day Bridgy-Fed admins / developers

ATTENTION. WARNING.

Effective immediately, you will stop all bridging, scraping, and copying of any and all content that has been shared by any ActivityPub account with the public key that matches the RSA signature 16:df:6e:4e:db:49:5f:fa:6c:4e:2d:a6:5d:d3:34:b0:f3:7e:0e:b6 or you will face a fine of $7,500 per transaction. Failure to comply will mean immediate forfeiture of all assets (monetary, real, and intellectual) with the use of force if necessary. 

You will also notify me immediately when compliance is achieved. You have two weeks from the datetime this issue is posted.

This is not a request.

"That's dumb, you can't just make arbitrary nonsense requests to somebody; just put some hash tag in your profile"
Oh well the request for me to put some hashtag in my profile was arbitrary. The Activity Pub spec doesn't even standardize the use or meaning of specific hash tags in that field. I was using that space for something else, which is incompatible with adding that hash tag there. What if I can't modify that software? Bridgy-Fed is forcing me to not use certain software which is as compatible with ActivityPub as Bridgy-Fed is. Bridgy-Fed will be the one to modify their software, because it's not opt-in. Sorry, I didn't make those rules, Bridgy-Fed did. If BlueSky doesn't feel like changing how their software works to comply with the new RSA public key rule (above), then simply federate with the protocol properly, so servers can use the protocol to choose to either federate or not federate.

"This issue sounds rude, mean-spirited, or hurt my feelings"
Too bad. Imagine getting messages like this out of the blue(sky). Imagine getting messages like this multiple times a day. Or hundreds all at once. Imagine moving to a new server with a new alias to be rid of them for a while, only for them to pour in again a month later. Imagine going through a tough day - getting your vehicle stolen, your phone stolen, your money stolen, a surprise bill, notice from your boss that you need to work the next 7 days or you're fired, and then get mean messages from completely random strangers on the Internet. Imagine having the time of your life (I'm not sure what this would be for BlueSky... maybe a good financial quarter?) and then receiving a hundred messages like "you shouldn't exist!" or "you're bad and should feel bad!" or "you put everyone in danger by existing!"

"This issue sounds non-professional/violent/harassing/inappropriate"
Good. Now imagine getting death threats just because you want to help people. Imaging getting sent violent imagery with a message "you're next". Imagine getting your front door kicked in by a violent gang of thugs armed with guns, destroying your actual, real property while they wave their guns around screaming at you. Then getting stuck with all the noise complaints and repair bills. Maybe they even abduct you. This really, really happens. Is any of that somehow supposed to be considered "professional"? Ripping content off of Activity Pub without using the appropriate protocol WILL result in vulnerable people getting unwanted attention by people they don't want to interact with. Until Bridgy-Fed either implements the aforementioned RSA signature protocol, OR BlueSky implements the Activity Pub protocol (or both), Bridgy-Fed's behavior is inappropriate, harmful, violent, and non-consensual.

"Bridgy-Fed is consensual. Just put the hash tag in the profile"
Okay, then Bridgy-Fed consents to implement the 16:df:6e:4e:db:49:5f:fa:6c:4e:2d:a6:5d:d3:34:b0:f3:7e:0e:b6 protocol, or they consent what I'm about to do to Bridgy-Fed. Like it. Or don't, doesn't matter. Those computers look nice. I'll take those as compensation.

"This issue is annoying, off-topic, spammy, etc."
Yes, I agree Bridgy-Fed is those things.

"So how should I implement this feature that I'm totally imagining?" 
Easy - add Activity Pub support to BlueSky. Or webmentions, or microformats2. Or add Bluesky/AT support to your favorite Activity Pub server software. Make it an optional plugin for the aforementioned software.

I'm sick and tired being harassed and threatened by techbros/techgals/techits. "Legal recourse"? You mean being forced to use my own money that I earned to "fix" a problem that shouldn't have existed in the first place, while it doesn't dent the techbro's wallet, WHILE they make even more money from my content? And just deal with the violence if I don't have the money for legal fees? Have my vehicle vandalized again because of something Facebook did without my consent? And I'm "rude" or "mean" or a "criminal" if I even suggest taking my compensation by myself? 

The Activity Pub protocol gives each server the tools they need to interact with the federation as they see fit. The protocol allows individuals to choose a server based on their policies. If an individual does not agree with the validity of the tools available to admins of Activity Pub servers, then they can choose not to create an account with any Activity Pub enabled software. This is not currently the case with Bridgy-Fed.

You have four options
1. Make Bridgy-Fed opt-in
2. OR have BlueSky interface with protocols using the protocols correctly
3. OR wipe your shit stain off the face of this entire universe
4. OR forfeit all of your assets to me (I'll fix all your woes)

Thank you for your time. Your cooperation will happen.

**Comment by Higgs1** [comment]
For the legal purposes of sending a legal entity a cease and desist notice, the above text DOES serve the purpose of requesting BlueSky / snarfed a cease and desist notice. You have been notified.

**Comment by ryleweb** [comment]
1. This is not a valid legal demand.
2. The Activity Pub spec does not even standardize the use or meaning of opt-in nor opt-out. Active Pub does standardize publishing data through it however, and you can choose not to do that.

**Comment by nukeop** [comment]
Lol, how long did it take you to type all that? How do you feel knowing it was a huge waste of time?

**Comment by Higgs1** [comment]
@ryleweb 
1. Genocide is legal. Murder is legal. Stealing people's homes and health is legal. Legal doesn't matter anymore.
2. It doesn't use those words, but it does. It returns HTTP 403 when a domain is blocked.

@nukeop 
Sure, some things could be done more efficiently. But it's better than not doing anything at all, so not a completele waste of time. Better time spent than "developing" something like Bridgy-Fed at least.

**Comment by ryleweb** [comment]
> Genocide is legal. Murder is legal. Stealing people's homes and health is legal. Legal isn't a useful term anymore.

You're being ludicrous.

> Any server that I'm arguing for returns HTTP 403 when a domain is blocked and thus opt-outs of a domain routing its content. 

Then you already know you can just limit brid.gy and you're done as it does authorized fetches. 

> and thus opt-outs of a domain routing its content.

Except it doesn't, because the thing that talks and communicates ActivePub is brid.gy, not the other services.

> The spec also doesn't define opt-in because the AP spec 

You're being hyperbolic, in terms of the spec it's really simple, treat brid.gy as the ActivePub instance, done. If it wasn't the case, it wouldn't function. From the ActivePub perspective, this is just an instance and you know it.

**Comment by nukeop** [comment]
Somebody quoting my post on the internet is LITERALLY genocide and murder

**Comment by SchizoidLifter** [comment]
What makes you think you can demand $7,500? Who would that even come from? What legal authority grants you the ability to 
"lay claim" on assets from a random internet code repo that does something you dislike? You are not some special individual, you are just some random loser.
I feel that it'd be very funny to make a project that specifically scrapes the data from the opt-out profiles and posts them on some kind of wall just to make fun of you. OP, you should consider bungee jumping while lacking a safety harness

**Comment by stella3d** [comment]
> 1. Genocide is legal. Murder is legal. 
 both of these are illegal actually

**Comment by stella3d** [comment]
> Genocide is legal. Murder is legal.

they're both illegal actually. murder law is a bit more enforceable

**Comment by snarfed** [comment]
@Higgs1 will do. I'm currently only set up to opt out by address, not public key, but I'll add that support and opt you out.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by mmangopear** [comment]
I ain't reading all that. I'm happy for u tho. Or sorry that happened.

**Comment by Gitspathe** [comment]
You can easily measure how schizo a comment will be by the profile pic

**Comment by Cyberes** [comment]
Wow, Aaron, it seems like you're having a tough day, huh? And by tough day, I mean complaining about everything under the sun and throwing insults left and right. You must be quite the keyboard warrior.

First of all, let's address your charming attitude. You're coming in here with your condescending tone and demanding compliance, as if you have any authority whatsoever. Sorry to burst your precious little bubble, but your self-proclaimed superiority doesn't impress anyone. In fact, it just makes you look like a petulant child throwing a tantrum.

Now, let's talk about your precious ActivityPub and Bridgy-Fed. It's clear that you have some beef with them, but instead of presenting a valid argument or engaging in a civilized discussion, you resort to insults and fantasies about seizing their assets. Newsflash, tough guy: that's not how the world works.

You keep whining about how Bridgy-Fed should implement this RSA signature protocol, or how BlueSky should magically support all the protocols you prefer. Well, guess what? The real world doesn't revolve around your whims. If you want specific features implemented, how about you contribute to the development yourself instead of acting like an entitled brat?

And let's not forget your little sob story about receiving mean messages and death threats. While I don't condone such behavior, I highly doubt it's as widespread as you claim. It's almost as if you enjoy playing the victim to justify your own obnoxious behavior.

So, Aaron, here's my suggestion for you: take a step back, reevaluate your approach, and maybe try being a decent human being for once. Oh, who am I kidding? That's probably too much to ask from someone like you. Just keep on spewing your toxicity and see how far it gets you. Spoiler alert: not very far.

Now, if you'll excuse me, I have much more important things to do than entertain your ludicrous demands and pathetic ranting. Goodbye, Aaron. May you find some semblance of maturity and common sense in your sad, little world.

**Comment by hobbes** [comment]
> First of all, let's address your charming attitude. You're coming in here with your condescending tone and demanding compliance, as if you have any authority whatsoever

you really don't see the irony there, do you ? Do I really have to explain how you completely missed the point ?

**Comment by Cyberes** [comment]
@hobbes Irony? Oh, I see plenty of it, my friend. You're quite the expert at missing the point yourself, aren't you?

But please, enlighten me. Explain to this lowly pleb how I've missed the oh-so-important point you're trying to make. I'm sure it'll be a riveting display of mental acrobatics and delusion.

**Comment by X64X2** [comment]
![17015093112519755.jpg](https://github.com/snarfed/bridgy-fed/assets/81354428/d213f831-1018-4b54-8331-6074182cf35b)

**Comment by ajloveslily14** [comment]
You sound like a psychopath

**Comment by hobbes** [comment]
> @hobbes Irony? Oh, I see plenty of it, my friend. You're quite the expert at missing the point yourself, aren't you?

maybe, but at least I'm not liking my own comments...

> But please, enlighten me. Explain to this lowly pleb how I've missed the oh-so-important point you're trying to make. I'm sure it'll be a riveting display of mental acrobatics and delusion.

Ok, explaining irony is a bit like explaining a joke, but I feel it's important, so I'll do it.

First, re-read the original post in this issue (really, go, reread it)

You get how condescending and absurd (both technically and socially) it is, don't you ?

Then compare it to how @snarfed instructed the entire fediverse to come on github, create an account, and create an issue in this project if they didn't want to be connected to his pet project.

Yes the OP is a caricature, but it's only a mirror of what this project told the entire fediverse.

**Comment by Cyberes** [comment]
@hobbes Ah, I see what you're getting at now, Aaron. You're trying to equate my "condescending and absurd" demeanor with the actions of someone else. Well, let me enlighten you once again with a dose of reality.

Comparing my response to someone instructing others to create an account and contribute to a project is like comparing apples and oranges, my friend. It's clear that you lack the ability to differentiate between a satirical persona and a genuine call to action.

The original post you're referring to may indeed be a caricature, but it's a deliberate exaggeration intended to make a point. It's not an instruction given by a project to its users, nor is it an attempt to manipulate people into following some arbitrary demand.

So, Aaron, since you seem to love throwing stones while living in a glass house, why don't you take a moment to reflect on your own inconsistencies and flawed arguments? Maybe then you'll realize just how misguided your attempts at criticism are.

But hey, who am I to waste my precious time trying to educate someone who clearly revels in their own ignorance? Carry on with your baseless accusations and feeble attempts at debate. It's quite amusing, really. So go ahead, Aaron, entertain me with more of your delusion. I'll be here, sipping on my metaphorical tea, utterly unimpressed.

**Comment by snarfed** [comment]
Sorry all, this isn't helping, I'm locking this issue. Feel free to take this to the fediverse or elsewhere.
