### ISSUE TITLE
domain opt-out

### ISSUE THREAD

**Issue by heartles** [snarfed/bridgy-fed#877]
i'm jaina heartles, the admin of `egirls.gay`. i am opting-out my entire domain along with any subdomains from your bridge. while my instance runs in allowlist mode and i will not be adding your bridge's domain to the list, i would like to make sure the block is mutual.

unfortunately i cannot dm you as i do not and will not federate with indieweb.social, but you can rest assured that i `@heartles` am the same jaina heartles as `@heartles@egirls.gay`, the listed administrator.

**Comment by Cyberes** [comment]
>allowlist
https://github.com/HomeITAdmin/nextcloud_geoblocker/issues/127

**Comment by snarfed** [comment]
Hi @heartles. If your instance does allowlist-based federation, and you don't add bsky.brid.gy, that will have the same effect as opting out in the bridge itself.

Having said that, I'm still happy to opt out your instance. I believe you that you're the admin, but I do need to confirm it. https://egirls.gay/@heartles doesn't work for me, I get "An error occurred" with a Retry button, which I'm guessing is expected.

Could you maybe email github@ryanb.org from an egirls.gay email address? That email will probably be DKIM-authenticated. Otherwise, I'm open any other way you'd want to demonstrate that you're the admin.

egirls.gay email address

**Comment by heartles** [comment]
shot you an email from the admin email listed on the instance's [about page](https://egirls.gay/about)

**Comment by snarfed** [comment]
Got it, thank you. I've opted out your domain.
