### ISSUE TITLE
Documentation on Privacy and the Fediverse

### ISSUE THREAD

**Issue by WisTex** [snarfed/bridgy-fed#881]
Based on the posts I have seen, a lot of people don't understand what "public" means, and they are using fediverse software that does not support privacy and access control. 

Adding a page about how privacy works in the fediverse would be a good thing, along with the definition of public.

Also, you should also consider recommending that people stop using Mastodon and switch to a platform that has better privacy and moderation tools. There are several platforms that are available, and many of them are connected to ActivityPub, so they can still talk to their Mastodon friends, just this time with more control over how their posts are distributed to the world.

As we can see from the reactions to the bridge, people don't think that Mastodon has sufficient privacy and moderation tools to protect them. If people want or need more protection, they should switch to software that provides that protection. And software like that is already available on the fediverse.

Having some articles on your website explaining that would probably help a bit.

**Comment by hobbes** [comment]
Based on the posts I have seen, a lot of people (you included) don't understand that publicly accessible data is not public data. 

The fact that you can publicly access some data *does not mean* that that data is public.

Youtube content is publicly accessible. Facebook's design material is publicly accessible. Disney's characters are publicly accessible. Microsoft Windows's installation media is publicly accessible. None of those are public data, by a very long shot. 

Try to use Disney characters in your designs, and see what happens (no really, actually don't, nobody deserves a Disney lawyer at his door)

Of course the problem here is not the same, but you base your reasoning on the fact that the data is publicly accessible on mastodon. Well, that does not make it public data, or mean that you can do anything you want with it.

**Comment by WisTex** [comment]
I never said that just because it was public people can do whatever they want with it. I was just saying that if you don't want people to read it, you probably should not make it public.

Also, there are fediverse projects that give you much more control over who can reply and comment on your posts. Mastodon does not support this, but other platforms do.

So even if you keep everything public, if you don't want people to reply to your posts, you should switch to a platform that allows you to restrict commenting on your posts.

**Comment by hobbes** [comment]
> I never said that just because it was public people can do whatever they want with it. I was just saying that if you don't want people to read it, you probably should not make it public.

I obviously do want people to read it, otherwise what would be the point ? You argue that the software I use does not support privacy. But privacy is not a technical problem, it's a social (and legal) one. Secrecy is a technical problem, not privacy. 

An example: right now, I don't have a door for my toilets (don't ask, construction work does not always go as planned). Do you think that as a family, we took that lack of door as authorization to go and see what everyone does there ? Or that we automatically installed the habit of being *very* vocal about our desire to use the toilets to be absolutely certain that nobody was there before we got in the critical zone ? There is no secrecy, everyone knows what one does there. But there is privacy, even without a door.

The fact that the fediverse does not have many doors does not mean that it's public ant I'm open to all my data being available on another social network. I chose the fediverse, not bluesky, or meta, or X, or... Don't equate publicly available with authorization to do anything with it but what **I** do with it.

**Comment by snarfed** [comment]
Thanks for the conversation, all! There are definitely different expectations around norms and what "public" means in the fediverse and beyond, and for good reasons. [I've written about this myself](https://snarfed.org/2024-01-19_moderate-people-not-code), and [linked to it from the Bridgy Fed docs in a few places](https://fed.brid.gy/docs#moderation-policy).

It's also not clear how much we need to change our expectations and desires vs changing the underlying technology (like ActivityPub) itself. Technology should serve people, not the other way around, obviously.

Beyond that, the overall debate is bigger and more important than Bridgy Fed itself, so I'd expect more to participate and link to it elsewhere than try to write comprehensively and authoritatively about it here. I'll keep it in mind though!

**Comment by WisTex** [comment]
The fediverse is actually older than Mastodon or ActivityPub. It has always been multi-protocol. The biggest problem I see is that people didn't understand what they signed up for when they signed up.
