### ISSUE TITLE
Change Bluesky abbreviation from `atproto` to `bsky`

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#961]
Eg `@snarfed.org` in Bluesky would be `@snarfed.org@bsky.brid.gy` in the fediverse instead of `@snarfed.org@atproto.brid.gy`. Seems a bit more user-friendly and memorable.

**Comment by qazmlp** [comment]
Wouldn't this normally the remote protocol, e.g. that `@snarfed.bsky.social` would be `@snarfed.bsky.social@bsky.brid.gy` instead of `@snarfed.bsky.social@atproto.brid.gy` in AP?

In Bluesky I would expect to see `@snarfed.indieweb.social.ap.brid.gy` or `@….nostr.brid.gy` handles for the other networks. Maybe I'm confused about this, though.

**Comment by snarfed** [comment]
Hah yes sorry, good catch, I got the example backward. Fixed now!

**Comment by snarfed** [comment]
Done!
