### ISSUE TITLE
AP => Bluesky: add link to original post if truncated

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#986]
Related to #976

**Comment by snarfed** [comment]
More ideas in #1002! (Merged in here.)

**Comment by Fauli1221** [comment]
Would that also apply to media Bluesky doesn't support like Videos and Audio?

**Comment by snarfed** [comment]
Maybe!

**Comment by snarfed** [comment]
Done! Example: https://indieweb.social/@snarfed/112441080098401081 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3kshvvi466tb2 . Presentation could be better, ideally we'd include an image if available, but it's a start.

<img width="610" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/618b4976-b791-4176-b25b-aba10ae0b94a">

**Comment by mackuba** [comment]
Hmm, suggestion: maybe do "(…)" instead of just "…" at the end? It's not immediately clear that the post was truncated and is not just a normal post that just happens to end the sentence with an ellipsis…

Current:

<p><img width="601" alt="Screen Shot 2024-05-29 at 22 57 53" src="https://github.com/snarfed/bridgy-fed/assets/28465/dc8adf74-e106-49cd-bde5-3fff1f59b5bf"></p>

Proposed:

<p><img width="601" alt="Screen Shot 2024-05-29 at 22 59 54" src="https://github.com/snarfed/bridgy-fed/assets/28465/a2ac857e-c2c8-4903-982e-3a32a1a45401"></p>

**Comment by snarfed** [comment]
Good point! Reopening.

**Comment by mackuba** [comment]
Btw, I'm adding a way to load the full contents from the Mastodon API and paste it inline to Skythread now 🙂

<img width="872" alt="Screen Shot 2024-05-30 at 00 28 04" src="https://github.com/snarfed/bridgy-fed/assets/28465/12b5668f-84b2-474b-be1e-7c2a6acf7542">

<img width="878" alt="Screen Shot 2024-05-30 at 00 30 20" src="https://github.com/snarfed/bridgy-fed/assets/28465/8a324429-8f5d-424c-a650-540a9e95daf5">

**Comment by snarfed** [comment]
Oh, awesome! Or you could fetch it via AP. You'd need to sign those fetches and serve a minimal AP actor with the public key; not sure if that's net more or less work than registering Mastodon OAuth clients dynamically per instance.

**Comment by snarfed** [comment]
That gives me another idea: I should store the full text in a custom field in the Bluesky record!

**Comment by mackuba** [comment]
> That gives me another idea: I should store the full text in a custom field in the Bluesky record!

Omg yes!!

**Comment by mackuba** [comment]
> Oh, awesome! Or you could fetch it via AP. You'd need to sign those fetches and serve a minimal AP actor with the public key; not sure if that's net more or less work than registering Mastodon OAuth clients dynamically per instance.

I haven't worked with the "low-level" AP API at all yet, just with the Mastodon REST one… and it's just one simple fetch here: https://github.com/mackuba/skythread/commit/540a8b2bd96393b341cb3471b9aba268dc515cc7#diff-1989dcd9cd0d832606735cbad270705ed51ae39d039b915672d37c9828e2da25R388 (it won't work for non-Mastodon instances, but I guess that won't be needed if you add that field :)

**Comment by snarfed** [comment]
Oh right, I forgot that big chunks of the Mastodon API are open, no auth needed. sgtm!

**Comment by jonpincus** [comment]
> (it won't work for non-Mastodon instances, but I guess that won't be needed if you add that field :)

A lot of non-Mastodon instances support the API so that apps work so you might be okay

**Comment by snarfed** [comment]
> I feel like this would be a good solution to content warning as well just have the CW and then load full post maybe

The catch is that we have no control over client UIs, whether official ones like https://bsky.app/ and the mobile apps or any others. We can't add a "load full post" button or link.

**Comment by qazmlp** [comment]
I think it would still be useful to have the full CN text[^1] and hidden text as custom fields on the bridged posts, both distinct from the mechanism for text that was just truncated to avoid mixups. That would allow third party apps to implement this flow without hitting the origin instance (i.e. better for privacy) or worrying about whether it supports the Mastodon API or if there's an implementation difference on the AP level.

[^1]: or a fragment indicating which part of the text is the CN, as that way you don't have to worry *as* much about whether UIs validate it matches presentation on Bsky, in case other PDSs use your lexicon to spoof something there.

**Comment by snarfed** [comment]
Anyone know the etiquette for choosing field names for custom fields in `app.bsky.*` lexicons that you don't know. I'm not sure what to name these fields. eg `fullText`, `bridgyFedFullText`, `fediverseFullText`, `bridgyFedFediverseFullText`, ...?

**Comment by snarfed** [comment]
Next step for changing the ellipsis string is to parameterize `brevity.shorten` to take a new `ellipsis='...'` kwarg: https://github.com/snarfed/brevity/blob/bb3cb14d2225c5401b010648e3e0e1158d82ba4c/brevity.py#L242-L245

**Comment by qazmlp** [comment]
> Anyone know the etiquette for choosing field names for custom fields in `app.bsky.*` lexicons that you don't own? I'm not sure what to name these fields. eg `fullText`, `bridgyFedFullText`, `fediverseFullText`, `bridgyFedFediverseFullText`, ...?

I think the answer to that is basically 'don't', according to https://atproto.com/specs/lexicon#authority-and-control.

Is there a way to specify a secondary NSID similarly to how you can import multiple namespaces in AP?

**Comment by snarfed** [comment]
> Is there a way to specify a secondary NSID similarly to how you can import multiple namespaces in AP?

No, there isn't. This is the way to add custom fields to existing records so that they're available to clients and other services. There's already plenty of precedent for it in the ATProto ecosystem! It's true that the docs you linked say:

> This is not the recommended way to extend applications, but it is not specifically disallowed.

...but there's no other realistic extension pattern yet.

I guess one way would be to store our own separate records, and publish logic for finding those records. That's _much_ less discoverable or usable than custom fields in existing records though. I haven't heard of any external developers using "sidecar" records like that yet.

**Comment by mackuba** [comment]
> Anyone know the etiquette for choosing field names for custom fields in `app.bsky.*` lexicons that you don't own? I'm not sure what to name these fields. eg `fullText`, `bridgyFedFullText`, `fediverseFullText`, `bridgyFedFediverseFullText`, ...?

Hey! I've done some digging for this today. It looks like we're still at the stage where there aren't really any clear conventions for this, or to put it differently, the stage where the conventions are being formed by what we're doing ;)

I've scanned the last few days worth of posts for unexpected record keys, and it looks like the only one of this kind is from the Skeets app by @seboslaw, which I think uses this for the post editing feature. The key there is named `skeetsAppHistory`.

There are also several non-standard but very generic-sounding keys (and probably in most cases added by mistake), like: `via`, `type`, `alt`, `labels` etc. This is probably not a good idea.

Some (inconclusive) threads I've found about this:

- https://github.com/bluesky-social/atproto/discussions/1889
- https://github.com/bluesky-social/atproto/discussions/2126
- thread from @seboslaw here on Discord: https://discord.com/channels/1097580399187738645/1097580399187738648/1209469681547747388
  - and subthread: https://discord.com/channels/1097580399187738645/1209471751625641994
  - and another: https://discord.com/channels/1097580399187738645/1202968500319031308
- thread from @badlogic: https://discord.com/channels/1097580399187738645/1097580399187738648/1175608584881569792
  - Mario has apparently used this to store custom fields in the profile record instead to store some user settings there - looks like the key is `social.skychat.settings`

As I understand it, something like `gy.brid.fed.originalPost` would probably be technically more "correct". But it looks ugly ;) Something like `bridgyOriginalPost`, `bridgyOriginalPostContent` or `bridgyFedFullText` looks better imho and I would go in this direction (we can bikeshed a bit about the specific name). In any case, apps will probably eventually use both of these conventions and more, and ultimately what matters is only that a key is well defined & documented so that others can make use of it if it makes sense, and to minimize the probability of collisions between 3rd party and Bluesky and between two 3rd parties by doing *anything* in that direction… I'd think that anything that starts with "bridgy" is extremely unlikely to accidentally create a collision with anything else.

(tagging also @bnewbold)

**Comment by snarfed** [comment]
Wow, thanks for the detailed investigation @mackuba!

Moving to #1092

**Comment by qazmlp** [comment]
> Hmm, suggestion: maybe do "(…)" instead of just "…" at the end? It's not immediately clear that the post was truncated and is not just a normal post that just happens to end the sentence with an ellipsis…

I just ran into that issue and would like to request the same 😅

Another suggestion, but rather than "Original post on …" I'd like to see

- "Read more on …"
- "See full text and 2 images on …"
- eventually (where applicable) also e.g. "See 1 video on …" if all text is present but some media was truncated

since that feels more descriptive of what can be expected after navigation.

**Comment by snarfed** [comment]
Agreed on `[...]`! I've switched to that for both posts and bios. Examples: https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3kumap43apaj2 , https://bsky.app/profile/evan.cosocial.ca.ap.brid.gy

**Comment by mackuba** [comment]
Hmm, have you changed something there to add the link to original inside the post body instead of as an embed?

**Comment by snarfed** [comment]
Good eye! Yes, only for posts with images, since Bluesky can't do both images and link embeds in the same post. 😕 Background in https://github.com/snarfed/bridgy-fed/issues/1106#issuecomment-2159748691 and https://github.com/bluesky-social/atproto/discussions/2575 .

**Comment by mackuba** [comment]
Ahh, ok, makes sense. I was worried this was a change for all truncated posts :) I saw the discussions about the different embed types, but I didn't realize it was about this. Not ideal, but it will have to do in this case. I think it's better to have this inconsistency with posts w/o images, because otherwise we lose a lot of space for text in those too.

**Comment by mackuba** [comment]
Alternatively, you could possibly link just the "[...]" to the original post instead of adding a second `[]` with "original post" below? But that might be not obvious enough I guess.

Like:

<p>This is a very long post that was truncated becase <a href="https://mastodon.social">[...]</a>.</p>
