### ISSUE TITLE
Bluesky: bridge deletes (blocked on switching from notifs to firehose)

### ISSUE THREAD

**Issue by goeo-** [snarfed/bridgy-fed#987]
A deleted post on Bluesky should also be deleted on the bridged ActivityPub account.

**Comment by snarfed** [comment]
Yes! Definitely agreed. This already works for some protocol pairs, eg web => AP, but maybe not Bluesky => AP yet. Will look.

**Comment by snarfed** [comment]
Ah. The problem here is that we don't get a notification anywhere when a Bluesky user deletes a post. Right now, to detect deletes, we'd need to regularly reload and check every single post we've bridged for that user. Hrm.

The alternative is #978, whch I _think_ we could use to reliably and immediately detect and bridge deletes. I may lean toward that.

**Comment by snarfed** [comment]
Done! Tested both directions just now, deletes are working.
